# Generated by Django 5.2.6 on 2025-09-26 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoPermissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContaContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('aceita_lancamento', models.BooleanField(default=True)),
                ('ativa', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhas', to='core.contacontabil')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('documento', models.CharField(max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_fornecedores', to='core.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'documento')},
            },
        ),
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_emissao', models.DateField()),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('data_baixa', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('provisao', 'Provisão'), ('baixado', 'Baixado'), ('estornado', 'Estornado')], default='provisao', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente_fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.clientefornecedor')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_financeiros', to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='LancamentoContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito')], max_length=7)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contacontabil')),
                ('lancamento_financeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_contabeis', to='core.lancamentofinanceiro')),
            ],
        ),
        migrations.CreateModel(
            name='PlanoContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='core.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='contacontabil',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='core.planocontas'),
        ),
        migrations.CreateModel(
            name='TipoLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('ativo', models.BooleanField(default=True)),
                ('conta_baixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_baixa', to='core.contacontabil')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_lancamento', to='core.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='tipo_lancamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipolancamento'),
        ),
        migrations.CreateModel(
            name='TipoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('ativo', models.BooleanField(default=True)),
                ('conta_credito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_credito', to='core.contacontabil')),
                ('conta_debito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_debito', to='core.contacontabil')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_movimentacao', to='core.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='tipo_movimentacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipomovimentacao'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.empresa')),
                ('grupos', models.ManyToManyField(blank=True, related_name='usuarios', to='core.grupopermissao')),
            ],
            options={
                'unique_together': {('empresa', 'login')},
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade', models.CharField(max_length=100)),
                ('operacao', models.CharField(max_length=20)),
                ('registro_id', models.IntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('detalhes', models.JSONField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='core.empresa')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usuario')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='contacontabil',
            unique_together={('plano', 'codigo')},
        ),
    ]
