# Generated by Django 5.2.7 on 2025-10-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('access_tela1', 'Pode acessar Tela 1'), ('access_tela2', 'Pode acessar Tela 2'), ('access_tela3', 'Pode acessar Tela 3')], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
