# Generated by Django 5.2.7 on 2025-10-10 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_alter_customuser_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('access_tela1', 'Pode acessar Tela 1'), ('access_tela2', 'Pode acessar Tela 2'), ('access_tela3', 'Pode acessar Tela 3'), ('access_suport', 'Pode acessar suporte')], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
